@define-color foreground {{ foreground }};
@define-color background {{ background }};
@define-color accent {{ accent }};
@define-color dim {{ color8 }};
@define-color surface {{ selection_background }};
@define-color primary {{ color4 }};
@define-color secondary {{ color5 }};
@define-color warning {{ color3 }};
@define-color error {{ color1 }};
