let
  secret = name: file: { inherit name file; };
in
[
  (secret "credentials/glab-token" ../../../secrets/credentials/glab-token.age)
  (secret "credentials/jira-api-token" ../../../secrets/credentials/jira-api-token.age)
  (secret "api-keys/sonarqube-token" ../../../secrets/api-keys/sonarqube-token.age)
  (secret "api-keys/brave-api-key" ../../../secrets/api-keys/brave-api-key.age)
  (secret "api-keys/deepgram-api-key" ../../../secrets/api-keys/deepgram-api-key.age)
  (secret "api-keys/gemini-api-key" ../../../secrets/api-keys/gemini-api-key.age)
  (secret "api-keys/klipy-api-key" ../../../secrets/api-keys/klipy-api-key.age)
  (secret "api-keys/nvidia-api-key" ../../../secrets/api-keys/nvidia-api-key.age)
  (secret "api-keys/opencode-api-key" ../../../secrets/api-keys/opencode-api-key.age)
  (secret "api-keys/openai-api-key" ../../../secrets/api-keys/openai-api-key.age)
  (secret "api-keys/todoist-api-token" ../../../secrets/api-keys/todoist-api-token.age)
  (secret "infrastructure/telegram-ids" ../../../secrets/infrastructure/telegram-ids.age)
  (secret "infrastructure/ssh-hosts" ../../../secrets/infrastructure/ssh-hosts.age)
  (secret "credentials/x-username" ../../../secrets/credentials/x/x-username.age)
  (secret "credentials/x-email" ../../../secrets/credentials/x/x-email.age)
  (secret "credentials/x-password" ../../../secrets/credentials/x/x-password.age)
  (secret "credentials/x-cookies" ../../../secrets/credentials/x/x-cookies.age)
  (secret "bot-tokens/telegram-bot-token-jarvis" ../../../secrets/bot-tokens/telegram/telegram-bot-token-jarvis.age)
  (secret "bot-tokens/telegram-bot-token-golden" ../../../secrets/bot-tokens/telegram/telegram-bot-token-golden.age)
  (secret "bot-tokens/telegram-bot-token-clever" ../../../secrets/bot-tokens/telegram/telegram-bot-token-clever.age)
  (secret "bot-tokens/telegram-bot-token-robson" ../../../secrets/bot-tokens/telegram/telegram-bot-token-robson.age)
  (secret "bot-tokens/telegram-bot-token-jenny" ../../../secrets/bot-tokens/telegram/telegram-bot-token-jenny.age)
  (secret "bot-tokens/telegram-bot-token-monster" ../../../secrets/bot-tokens/telegram/telegram-bot-token-monster.age)
  (secret "bot-tokens/telegram-bot-token-silver" ../../../secrets/bot-tokens/telegram/telegram-bot-token-silver.age)
  (secret "bot-tokens/discord-bot-token-jarvis" ../../../secrets/bot-tokens/discord/discord-bot-token-jarvis.age)
  (secret "bot-tokens/discord-bot-token-golden" ../../../secrets/bot-tokens/discord/discord-bot-token-golden.age)
  (secret "bot-tokens/discord-bot-token-clever" ../../../secrets/bot-tokens/discord/discord-bot-token-clever.age)
  (secret "bot-tokens/discord-bot-token-robson" ../../../secrets/bot-tokens/discord/discord-bot-token-robson.age)
  (secret "bot-tokens/discord-bot-token-jenny" ../../../secrets/bot-tokens/discord/discord-bot-token-jenny.age)
  (secret "bot-tokens/discord-bot-token-monster" ../../../secrets/bot-tokens/discord/discord-bot-token-monster.age)
  (secret "bot-tokens/discord-bot-token-silver" ../../../secrets/bot-tokens/discord/discord-bot-token-silver.age)
  (secret "bot-tokens/discord-bot-token-claude" ../../../secrets/bot-tokens/discord/discord-bot-token-claude.age)
  (secret "discord-channels/discord-channels-monster" ../../../secrets/discord-channels/discord-channels-monster.age)
  (secret "credentials/obsidian-headless-auth-token" ../../../secrets/credentials/obsidian/obsidian-headless-auth-token.age)
  (secret "credentials/obsidian-headless-sync-config" ../../../secrets/credentials/obsidian/obsidian-headless-sync-config.age)
  (secret "infrastructure/gpg-private-key" ../../../secrets/infrastructure/gpg-private-key.age)
  (secret "credentials/viu-auth" ../../../secrets/credentials/viu-auth.age)
  (secret "credentials/home-assistant-token" ../../../secrets/credentials/home-assistant-token.age)
  (secret "credentials/google-totp-secret" ../../../secrets/credentials/google-totp-secret.age)
  (secret "credentials/gcp-usage-uploader-key" ../../../secrets/credentials/usage-reporting/gcp-usage-uploader-key.age)
  (secret "credentials/ingest-producer-secret" ../../../secrets/credentials/usage-reporting/ingest-producer-secret.age)
  (secret "credentials/bitwarden-client-id" ../../../secrets/credentials/bitwarden/bitwarden-client-id.age)
  (secret "credentials/bitwarden-client-secret" ../../../secrets/credentials/bitwarden/bitwarden-client-secret.age)
  (secret "credentials/bitwarden-master-password" ../../../secrets/credentials/bitwarden/bitwarden-master-password.age)
  (secret "infrastructure/kira-session-connector-credentials" ../../../secrets/infrastructure/kira-session-connector-credentials.age)
  (secret "infrastructure/rin-session-connector-credentials" ../../../secrets/infrastructure/rin-session-connector-credentials.age)
]
