var weatherIconMap = {
  0: "clear_day",
  1: "clear_day",
  2: "partly_cloudy_day",
  3: "cloud",
  45: "foggy",
  48: "foggy",
  51: "rainy",
  53: "rainy",
  55: "rainy",
  56: "rainy",
  57: "rainy",
  61: "rainy",
  63: "rainy",
  65: "rainy",
  66: "rainy",
  67: "rainy",
  71: "cloudy_snowing",
  73: "cloudy_snowing",
  75: "snowing_heavy",
  77: "cloudy_snowing",
  80: "rainy",
  81: "rainy",
  82: "rainy",
  85: "cloudy_snowing",
  86: "snowing_heavy",
  95: "thunderstorm",
  96: "thunderstorm",
  99: "thunderstorm",
};

var weatherConditionMap = {
  0: "Clear",
  1: "Clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Fog",
  51: "Drizzle",
  53: "Drizzle",
  55: "Drizzle",
  56: "Freezing drizzle",
  57: "Freezing drizzle",
  61: "Light rain",
  63: "Rain",
  65: "Heavy rain",
  66: "Light rain",
  67: "Heavy rain",
  71: "Light snow",
  73: "Snow",
  75: "Heavy snow",
  77: "Snow",
  80: "Light rain",
  81: "Rain",
  82: "Heavy rain",
  85: "Light snow showers",
  86: "Heavy snow showers",
  95: "Thunderstorm",
  96: "Thunderstorm with hail",
  99: "Thunderstorm with hail",
};
