{
    "useCustom": true,
    "TitleFore": "{{ foreground }}",
    "TitleBack": "{{ background }}",
    "TitleInfo": "{{ foreground }}",
    "NormalTitle": "{{ color1 }}",
    "DimmedTitle": "{{ color15 }}",
    "SelectedTitle": "{{ accent }}",
    "NormalDesc": "{{ color2 }}",
    "DimmedDesc": "{{ color15 }}",
    "SelectedDesc": "{{ accent }}",
    "StatusMsg": "{{ color4 }}",
    "PinIndicatorColor": "{{ color1 }}",
    "SelectedBorder": "{{ accent }}",
    "SelectedDescBorder": "{{ accent }}",
    "FilteredMatch": "{{ color1 }}",
    "FilterPrompt": "{{ color5 }}",
    "FilterInfo": "{{ foreground }}",
    "FilterText": "{{ cursor }}",
    "FilterCursor": "{{ color3 }}",
    "HelpKey": "{{ accent }}",
    "HelpDesc": "{{ foreground }}",
    "PageActiveDot": "{{ color2 }}",
    "PageInactiveDot": "{{ color15 }}",
    "DividerDot": "{{ color1 }}",
    "PreviewedText": "{{ foreground }}",
    "PreviewBorder": "{{ accent }}"
}
