accent = "#c17013"
cursor = "#f7f6f5"
foreground = "#f7f6f5"
background = "#041c38"
selection_foreground = "#041c38"
selection_background = "#f7f6f5"

color0 = "#041c38"
color1 = "#c17013"
color2 = "#239f7d"
color3 = "#b79319"
color4 = "#707fec"
color5 = "#707fec"
color6 = "#239f7d"
color7 = "#f7f6f5"
color8 = "#4f6073"
color9 = "#ed840b"
color10 = "#14d19e"
color11 = "#e5b40e"
color12 = "#707fec"
color13 = "#707fec"
color14 = "#14d19e"
color15 = "#fbfafa"
