$switcherSock = $XDG_RUNTIME_DIR/quickshell-switcher.sock

bind = SUPER, TAB, exec, printf 'open\n' | nc -U -N $switcherSock
bind = SUPER, TAB, submap, windowswitcher

bind = ALT, TAB, exec, printf 'open\n' | nc -U -N $switcherSock
bind = ALT, TAB, submap, windowswitcher

submap = windowswitcher
bind = SUPER, TAB, exec, printf 'next\n' | nc -U -N $switcherSock
bind = SUPER SHIFT, TAB, exec, printf 'prev\n' | nc -U -N $switcherSock
bind = ALT, TAB, exec, printf 'next\n' | nc -U -N $switcherSock
bind = ALT SHIFT, TAB, exec, printf 'prev\n' | nc -U -N $switcherSock
bind = , ESCAPE, exec, printf 'cancel\n' | nc -U -N $switcherSock
bind = , ESCAPE, submap, reset
bind = , RETURN, exec, printf 'confirm\n' | nc -U -N $switcherSock
bind = , RETURN, submap, reset
bindrt = ALT, ALT_L, exec, printf 'confirm\n' | nc -U -N $switcherSock
bindrt = ALT, ALT_L, submap, reset
bindrt = ALT SHIFT, ALT_L, exec, printf 'confirm\n' | nc -U -N $switcherSock
bindrt = ALT SHIFT, ALT_L, submap, reset
bindrt = SUPER, SUPER_L, exec, printf 'confirm\n' | nc -U -N $switcherSock
bindrt = SUPER, SUPER_L, submap, reset
bindrt = SUPER SHIFT, SUPER_L, exec, printf 'confirm\n' | nc -U -N $switcherSock
bindrt = SUPER SHIFT, SUPER_L, submap, reset
submap = reset
